### ISSUE TITLE
请求支持本地固件上传

### ISSUE THREAD

**Issue by OnDriveLine** [A5245/Wearable-Debug#4]
现在模块支持了表盘和第三方APP上传。为什么不追加一个固件上传）想要畅快刷固件惹

**Comment by A5245** [comment]
该功能过于危险，个人没有救砖能力的

**Comment by OnDriveLine** [comment]
> 该功能过于危险，个人没有救砖能力的

要不开启这个功能前加个二次确认？

**Comment by Searchstars** [comment]
1. Notify for Xiaomi、Gadget等应用皆拥有对设备进行固件刷写的功能，且已经存在数年之久，期间砖的肯定不少，但不会因为砖了就不提供这个功能。
2. 由于上面提到的两款软件属于小米运动健康的第三方实现，因此对于新设备的支持需要开发者手动抓包添加，这个issue的目的皆在于通过模块调用官方编写的逻辑代码，这样基本上可以直接适配好新设备的固件刷写，而自己则不需要重新抓包实现，对我们非常需要。
3. 手环/手表会对接收到的固件包进行校验与验签，验签这步使用RSA非对称加密，非常难以绕过，因此基本上只能刷写官方固件，变砖的可能性几乎没有。
