### ISSUE TITLE
修复表盘安装失败的问题

### ISSUE THREAD

**Issue by OnDriveLine** [A5245/Wearable-Debug#5]
在3.30.0i版本中，使用watchface按钮无法安装手环9表盘，尽管进度条在走动，手环9上无法显示

**Comment by A5245** [comment]
在3.30.0i版本在8Pro上测试正常，我没有9设备没法测试

**Comment by OnDriveLine** [comment]
经过测试，手环9/手环9Pro/小米watch s4/Redmi Watch 5皆无法通过watchface安装表盘，望开发者修复
