### ISSUE TITLE
能否增加拉取设备log功能

### ISSUE THREAD

**Issue by leset0ng** [A5245/Wearable-Debug#7]
在快应用开发过程中，一些事情模拟器无法复现，希望增加这个功能
![image](https://github.com/user-attachments/assets/88b03479-0967-4b66-977e-9179e12bb107)
这个是小米文档里面对此功能的描述

**Comment by Searchstars** [comment]
补充：设备日志目前可通过在运动健康中点击 我的 > 问题反馈 后创建一个附带固件日志的无效反馈获取，操作完成后设备日志会出现在com.mi.health的log文件夹中。作者可以考虑分析一下发送反馈按钮绑定的函数，从而定位到拉取设备日志的函数并进行hook

**Comment by leset0ng** [comment]
好的工作，使我获取到设备原木👍



------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2024年10月4日(星期五) 上午10:41
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [A5245/Wearable-Debug] 能否增加拉取设备log功能 (Issue #7)














 
补充：设备日志目前可通过在运动健康中点击 我的 &gt; 问题反馈 后创建一个附带固件日志的无效反馈获取，操作完成后设备日志会出现在com.mi.health的log文件夹中。作者可以考虑分析一下发送反馈按钮绑定的函数，从而定位到拉去设备日志的函数并进行hook

**Comment by A5245** [comment]
我用的国际版3.33.6i，进入About this app -> 快速点击应用图标就会保存日志

**Comment by leset0ng** [comment]
你这样操作保存的不是设备日志，是手机日志



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年10月4日(周五) 晚上7:20
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [A5245/Wearable-Debug] 能否增加拉取设备log功能 (Issue #7)




 
我用的国际版3.33.6i，进入About this app -&gt; 快速点击应用图标就会保存日志

**Comment by A5245** [comment]
已添加设备日志拉取
